<?php

/**
 * @file
 * Primary module hooks for Yelen Personnalisation module.
 */

use Drupal\Core\Render\Markup;

/**
 * Implements hook_page_attachments().
 */
function yelen_customization_page_attachments(array &$attachments) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $attachments['#attached']['library'][] = 'yelen_customization/admin_assets';
  }

  /*
   * Chargement du fichier local Matomo
   */

  $script = <<<JS
(function() {
  var s = document.createElement('script');
  s.type = 'text/javascript';
  s.async = true;
  s.src = location.origin + '/matomo/matomo.js';
  document.head.appendChild(s);
})();
JS;

  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#type' => 'html_tag',
      '#value' => Markup::create($script),
    ],
    'custom_matomo_script',
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function yelen_customization_preprocess_page(array &$variables) {
  $variables['#attached']['drupalSettings']['user'] = [
    'isLoggedIn' => \Drupal::currentUser()->isAuthenticated()
  ];
}


/**
 * Implements hook_views_data().
 */
function yelen_customization_views_data() {
  $data = [];

  $data['views']['year_filter'] = [
    'title' => t('Filtre par année de création - Filtre personnalisé'),
    'filter' => [
      'title' => t('Filtre par année de création - Filtre personnalisé'),
      'field' => 'created',
      'id' => 'year_filter',
    ],
  ];

  return $data;
}
