<?php

/**
 * @file
 * Primary module hooks for Yelen Personnalisation module.
 */

/**
 * Implements hook_page_attachments().
 */
function yelen_customization_page_attachments(array &$attachments) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $attachments['#attached']['library'][] = 'yelen_customization/admin_assets';
  }
}


/**
 * Implements hook_views_data().
 */
function yelen_customization_views_data() {
  $data = [];

  $data['views']['year_filter'] = [
    'title' => t('Filtre par année de création - Filtre personnalisé'),
    'filter' => [
      'title' => t('Filtre par année de création - Filtre personnalisé'),
      'field' => 'created',
      'id' => 'year_filter',
    ],
  ];

  return $data;
}
