<?php

/**
 * @file
 * Primary module hooks for Orange Yelen Trombino module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;
/**
 * @return array[]
 * @Implement hook_theme()
 */
function orange_yelen_trombino_theme(): array{
  return [
    'orange_yelen_trombino_index' => [
      'variables' => [],
    ],
    'trombino_point_service' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for trombino point service templates.
 *
 * Default template: trombino-point-service.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the trombino point service information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_trombino_point_service(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function orange_yelen_trombino_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish trombino point service.
      $storage = \Drupal::entityTypeManager()->getStorage('trombino_point_service');
      $trombino_point_service_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($trombino_point_service_ids) as $trombino_point_service) {
        $trombino_point_service->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize trombino point service.
      $storage = \Drupal::entityTypeManager()->getStorage('trombino_point_service');
      $trombino_point_service_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($trombino_point_service_ids) as $trombino_point_service) {
        $trombino_point_service->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function orange_yelen_trombino_user_predelete(UserInterface $account): void {
  // Delete trombino point service that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('trombino_point_service');
  $trombino_point_service_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($trombino_point_service_ids)
  );
}
