<?php

/**
 * @file
 * Primary module hooks for Orange Yelen Chat module.
 */

use Drupal\Core\Render\Element;

const TCHAT_VIEW_ID = 'yelen_chat';
const TCHAT_VIEW_CURRENT_DISPLAY = 'page_1';
const TCHAT_VIEW_PAGE_NAME = 'view.'.TCHAT_VIEW_ID.'.'.TCHAT_VIEW_CURRENT_DISPLAY;
const TCHAT_CANONICAL = 'entity.yelen_chat.canonical';
/**
 * Implements hook_theme().
 */
function orange_yelen_chat_theme(): array {
  return [
    'orange_yelen_chat' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for yelen tchat templates.
 *
 * Default template: orange-yelen-chat.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the yelen tchat information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_orange_yelen_chat(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implémentation de hook_preprocess_page().
 */
function orange_yelen_chat_preprocess_page(array &$variables) {
  // $variables['page']['content']['#markup'] = '<div id="chatApp"></div>';
  // $variables['page']['content']= '<div id="chatApp"></div>';
}

/**
 * Page_attachments_alter()
 */
function orange_yelen_chat_page_attachments_alter(&$page) {
  $current_user = \Drupal::currentUser();
  $is_current_route_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if (
    !$current_user->hasPermission('administer site configuration') && !$is_current_route_admin
  ) {
    $page['#attached']['library'][] = 'orange_yelen_chat/orange-yelen-chat';
  }

  /*if(_orange_yelen_chat__check_path()){
    $page['#attached']['library'][] = 'orange_yelen_chat/orange-yelen-chat';
  }*/
}

/**
 * Implements hook_page_attachments().
 */
function orange_yelen_chat_page_attachments(array &$attachments) {
  $current_user = \Drupal::currentUser();
  $attachments['#attached']['drupalSettings']['yelen_chat']['current_user'] =[
    'uid' => $current_user->id(),
    'name' => $current_user->getAccountName(),
  ];
}


/**
 * Implements hook_preprocess_HOOK().
 */
function orange_yelen_chat_preprocess_views_view_unformatted(&$variables) {
  if ($variables['view']->id() == 'messages_de_conversation') {
    // Ajoutez le formulaire au contexte Twig.
    $variables['reply_message_form'] = \Drupal::formBuilder()->getForm('Drupal\orange_yelen_chat\Form\ReplyMessageForm');
  }
}



function _orange_yelen_chat__check_path(): bool
{
  $route = \Drupal::routeMatch()->getRouteName();
  return $route === TCHAT_VIEW_PAGE_NAME || $route === TCHAT_CANONICAL;
}

