<?php


declare(strict_types=1);


use Drupal\yelen_notification\Constante\Constante;
use Drupal\Core\Entity\EntityInterface;
use Drupal\yelen_notification\Event\QuizNotificationEvent;

/**
 * Implements hook_entity_update().
 */
function yelen_access_quiz_quiz_update(EntityInterface $entity)
{
  $current_state = $entity->moderation_state->getValue()[0]['target_id'];
  $date = !empty($entity->quiz_date->getValue()) ? $entity->quiz_date->getValue()[0] : [];
  $description = !empty($entity->body->getValue()) ? $entity->body->getValue()[0]['value'] : null;
  $emailExtractorService = \Drupal::service('yelen_notification.extract.mail');
  $emails = $emailExtractorService->extractMailFromBroadcastList($entity, 'field_liste_de_diffusion');
  if ($current_state == Constante::PUBLISHED) {
    $event = new QuizNotificationEvent($entity->id(), $entity->label(), $emails, $date);
    $event->setDescription($description);
    $event_dispatcher = \Drupal::service('event_dispatcher');
    $event_dispatcher->dispatch($event, QuizNotificationEvent::PUBLISH_QUIZ);
  }
}
