---

- hosts: all
  become: false
  vars:
    tmp_dir: /var/tmp
  tasks:
    - name: Upload project source archive on server
      copy:
        src:  "{{ src_archive_file }}"
        dest: "{{ tmp_dir }}"

    - name: Upload project script archive on server
      copy:
        src:  "{{ bin_archive_file | basename }}"
        dest: "{{ tmp_dir }}"

    - name: Deploy project scripts
      command: "sudo /usr/local/sbin/apache-app-deploy -n {{ app_name }} -f {{ tmp_dir }}/{{ bin_archive_file }} -d bin"

    - name: Execute before deploy script
      command: "sudo /usr/local/sbin/apache-app-deploy-before -n {{ app_name }}"
      register: output

    - name: Execute before deploy script (Output)
      debug: var=output

    - name: Deploy App folder to htdocs
      command: "sudo /usr/local/sbin/apache-app-deploy -n {{ app_name }} -f {{ tmp_dir }}/{{ src_archive_file }}"

    - name: Install composer dependencies
      shell: |
        sudo bash -c "export COMPOSER_ALLOW_SUPERUSER=1 && cd /var/www/{{ app_name }}/htdocs/ && /usr/local/bin/composer install --no-interaction --no-scripts"

#    - name: composer install
#      command: "sudo /usr/local/sbin/composer-install"
#      register: output
#      ignore_errors: yes

    - name: Execute after deploy script
      command: "sudo /usr/local/sbin/apache-app-deploy-after -n {{ app_name }}"
      register: output

    #    - name: composer install
    #      command: "sudo /usr/local/sbin/install-composer"
    #      register: output
    #     ignore_errors: yes

    #  - name:  relance composer
    #    command: "sudo /usr/local/sbin/composer-install"
    #    register: output
    #    ignore_errors: yes

    - name: Cleanup
      file:
        path: "{{ tmp_dir }}/{{ src_archive_file }}"
        state: absent

