<?php

declare(strict_types=1);

/**
 * @file
 * Provides a liste diffusion entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function yelen_notification_theme(): array
{
  return [
    'broadcast_list' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for liste diffusion templates.
 *
 * Default template: broadcast-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the liste diffusion information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_broadcast_list(array &$variables): void
{
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

function yelen_notification_node_insert($node)
{
  $content_type = $node->getType();
  switch ($content_type) {
    case 'article':

      break;
    case 'faq':
      break;
    default:
      break;
  }
}
